### ISSUE TITLE
Fatal when creating users from the Drupal administration

### ISSUE THREAD

**Issue by nganivet** [PalanteJon/domain_civicrm#2]
A fatal error is thrown when creating users from the Drupal admin screen:
`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '816-5' for key 'PRIMARY': INSERT INTO {domain_editor} (uid, domain_id) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1); Array ( [:db_insert_placeholder_0] => 816 [:db_insert_placeholder_1] => 5 ) in domain_civicrm_civicrm_post() (line 26 of {SITE_PATH}/modules/domain_civicrm/domain_civicrm.module).`

This is most likely because the creation of a user in Drupal triggers the creation of a CiviCRM contact, which triggers the creation of a UFMatch record, which calls this function which then tries to create another entry for the same (uid, domain_id) in the domain_editor table.

The solution is to use a 'merge' query rather than an 'insert'. PR to follow.

**Comment by MegaphoneJon** [comment]
Thanks for catching this Nicolas!
